# Generated by Django 2.2.19 on 2021-05-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='marks',
            name='last_name',
            field=models.CharField(default='razi', max_length=200),
            preserve_default=False,
        ),
    ]
