# Generated by Django 2.2.19 on 2021-05-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210517_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'Marks'},
        ),
    ]
