# Generated by Django 2.2.19 on 2021-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210517_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'Mark', 'verbose_name_plural': 'Marks'},
        ),
        migrations.AlterField(
            model_name='marks',
            name='RollNumber',
            field=models.CharField(max_length=8),
        ),
    ]
